export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const FORGET_SUCCESS = "FORGET_SUCCESS";
export const FORGET_FAIL = "FORGET_FAIL";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

export const LOGOUT = "LOGOUT";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";

export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const EXPERIENCE_FAIL = "EXPERIENCE_FAIL";
export const EDUCATION_FAIL = "EDUCATION_FAIL";
export const PROFILE_FAIL = "PROFILE_FAIL";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const SET_ALERT_TOAST_IN = "SET_ALERT_TOAST_IN";
export const SET_ALERT_TOAST_OUT = "SET_ALERT_TOAST_OUT";
export const REMOVE_ALERT_ALERT = "REMOVE_ALERT_ALERT";

export const SEND_MESSAGE_CONTACT = "SEND_MESSAGE_CONTACT";
export const FAIL_MESSAGE_CONTACT = "FAIL_MESSAGE_CONTACT";

export const PROFESSIONAL_AREAS = "PROFESSIONAL_AREAS";
export const PROFESSIONAL_AREAS_ERROR = "PROFESSIONAL_AREAS_ERROR";
